// Bilingual guide source; keep API and static fallback lessons in sync.
import {readFileSync, writeFileSync} from 'node:fs';
const read = path => JSON.parse(readFileSync(new URL('../'+path, import.meta.url), 'utf8'));
const write = (path, text) => writeFileSync(new URL('../'+path, import.meta.url), text, 'utf8');
const lessons = read('content/games/huang/guide.json');
write('public/games/huang/guide-data.js', '// Generated by scripts/build_huang_guide.mjs.\nexport const lessons = '+JSON.stringify(lessons, null, 2)+';\n');
write('content/games/huang/lesson.json', JSON.stringify(lessons.en, null, 2)+'\n');
const fallback = read('public/data/games/huang.json');
fallback.lesson = lessons.en;
write('public/data/games/huang.json', JSON.stringify(fallback, null, 2)+'\n');
console.log(`Built ${lessons.en.steps.length} bilingual HUANG sections.`);
