"""Rebuild artwork-only guide crops from the supplied English rulebook.

Coordinates use the existing 1600px-high page renders. No rules text is
generated here; bilingual figure captions live in guide-examples.js.
"""
from pathlib import Path
import json
import pypdfium2 as pdfium
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / 'content/games/fate-of-the-fellowship'
PUBLIC = ROOT / 'public/guide-assets/fate-of-the-fellowship'
PDF = ROOT / 'content/games/fate-of-fellowshipe/ZMGPSM0101_Rulebook_English_WEB.pdf'

# A list of parts is assembled left-to-right, preserving spread relationships.
CROPS = {
    'board-features.webp': [(3, (53, 411, 1037, 1255))],
    'setup-board.webp': [(4, (530, 116, 1129, 1129)), (5, (0, 116, 582, 1129))],
    'player-deck.webp': [(8, (613, 785, 1102, 1230))],
    'travel-characters.webp': [(11, (70, 280, 533, 515))],
    'travel-troops.webp': [(11, (583, 256, 1047, 481))],
    'fellowship.webp': [(12, (92, 518, 570, 734))],
    'prepare.webp': [(12, (612, 1244, 1083, 1527))],
    'muster.webp': [(13, (45, 287, 523, 564))],
    'battle-after.webp': [(14, (132, 627, 749, 949))],
    'shadow-halves.webp': [(16, (595, 151, 1100, 342))],
    'shadow-flow.webp': [(16, (590, 419, 1080, 651))],
    'advance-battle.webp': [(17, (82, 1260, 1020, 1484))],
    'reinforce-battle.webp': [(18, (778, 926, 1000, 1146))],
    'nazgul-deploy.webp': [(18, (547, 1153, 1055, 1518))],
    'nazgul-approach.webp': [(19, (509, 77, 1070, 483))],
    'icon-friendship.webp': [(24, (113, 161, 153, 191))],
    'icon-valor.webp': [(24, (611, 157, 644, 190))],
    'icon-stealth.webp': [(24, (116, 299, 151, 336))],
    'icon-resistance.webp': [(24, (611, 299, 643, 327))],
}
# Exclude prose intruding into otherwise rectangular artwork bounds.
# These are page coordinates, not painted-over or regenerated illustrations.
EXCLUDED = {
    'nazgul-approach.webp': [(509, 330, 577, 483)],
    'player-deck.webp': [(613, 1000, 640, 1230)],
}
for name, row in [('slip', 1), ('weary', 2), ('exposed', 3), ('recall', 4),
                  ('rout', 6), ('exchange', 7), ('overrun', 8), ('nazgul', 9)]:
    y = 498 + row * 65
    CROPS[f'icon-{name}.webp'] = [(24, (753, y, 807, y + 57))]
for name, row in [('haven', 0), ('stronghold', 1), ('eye', 2), ('nazgul-piece', 3),
                  ('dwarven-location', 6), ('elven-location', 7),
                  ('rohirrim-location', 8), ('gondor-location', 9)]:
    y = 498 + row * 65
    x = 452 if name.endswith('-location') else 152
    CROPS[f'icon-{name}.webp'] = [(24, (x, y, x + 57, y + 57))]


def main():
    doc = pdfium.PdfDocument(PDF)
    pages = {}
    manifest = json.loads((CONTENT / 'image-sources.json').read_text(encoding='utf-8'))
    for name, parts in CROPS.items():
        pieces = []
        for number, box in parts:
            if number not in pages:
                page = doc[number - 1]
                pages[number] = page.render(scale=2400 / page.get_height()).to_pil().convert('RGB')
            piece = pages[number].crop(tuple(round(v * 1.5) for v in box)).convert('RGBA')
            for left, top, right, bottom in EXCLUDED.get(name, []):
                piece.paste((0, 0, 0, 0), tuple(round(v * 1.5) for v in (left-box[0], top-box[1], right-box[0], bottom-box[1])))
            pieces.append(piece)
        canvas = Image.new('RGBA', (sum(p.width for p in pieces), max(p.height for p in pieces)), (0, 0, 0, 0))
        x = 0
        for piece in pieces:
            canvas.paste(piece, (x, 0))
            x += piece.width
        for directory in [CONTENT / 'images', PUBLIC]:
            canvas.save(directory / name, 'WEBP', quality=92, method=6)
        manifest[name] = {'parts': [{'page': n, 'box': b} for n, b in parts], 'coordinateHeight': 1600, 'renderHeight': 2400}
        if name in EXCLUDED:
            manifest[name]['excludedProseBoxes'] = EXCLUDED[name]
    (CONTENT / 'image-sources.json').write_text(json.dumps(manifest, indent=2) + '\n', encoding='utf-8')
    sizes = {name: Image.open(PUBLIC / name).size for name in manifest}
    (ROOT / 'public/games/fate-of-the-fellowship/guide-image-sizes.js').write_text(
        '// Generated by scripts/build_fellowship_illustrations.py.\nexport const imageSizes = '
        + json.dumps(sizes, indent=2) + ';\n', encoding='utf-8')
    print(f'Built {len(CROPS)} artwork crops in content and public assets.')


if __name__ == '__main__':
    main()
