// One reviewed bilingual source feeds the static guide and the full chat context.
import {readFile, writeFile} from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const content = new URL('content/games/fate-of-the-fellowship/', root);
const web = new URL('public/games/fate-of-the-fellowship/', root);
const data = JSON.parse(await readFile(new URL('characters.json', content), 'utf8'));
const start = '<!-- fellowship-characters:start -->';
const end = '<!-- fellowship-characters:end -->';
for (const language of ['en', 'zh']) {
  const topic = data[language];
  const suffix = language === 'en' ? '.en' : '';
  await writeFile(new URL(`guide-characters${suffix}.js`, web),
    '// Generated by scripts/build_fellowship_characters.mjs; edit characters.json.\n' +
    `export const characterTopic = ${JSON.stringify(topic, null, 2)};\n`);
  const guideFile = new URL(`guide-data${suffix}.js`, web);
  let guide = await readFile(guideFile, 'utf8');
  const importLine = `import {characterTopic} from './guide-characters${suffix}.js';\n`;
  if (!guide.includes(importLine)) guide = importLine + guide;
  if (!guide.includes('topics.push(characterTopic);')) guide += '\ntopics.push(characterTopic);\n';
  await writeFile(guideFile, guide);
  const markdown = [start, `## ${topic.title}`, '',
    language === 'en' ? 'Source: supplied One Sheet To Rule Them All v1.6, p. 2; printed-card and online cross-checks recorded in character-review.md. This is a base-character summary, not a complete objective/event-card catalog.' : '来源：用户提供的 One Sheet To Rule Them All v1.6 第 2 页；角色卡与在线交叉核对记录见 character-review.md。这里总结基础角色能力，不是完整的目标卡／事件卡目录。',
    '', topic.key, '', ...topic.bullets.map(b => `- ${b}`), '',
    `| ${topic.table.headers.join(' | ')} |`, '| --- | --- |',
    ...topic.table.rows.map(row => `| ${row.join(' | ')} |`), '',
    ...topic.details.flatMap(d => [`### ${d.title}`, '', ...d.text.split('\n').map(line => `- ${line}`), '']), end, ''].join('\n');
  const rulesFile = new URL(`rules.${language}.md`, content);
  let rules = await readFile(rulesFile, 'utf8');
  if (rules.includes(start)) {
    const endIndex = rules.indexOf(end, rules.indexOf(start));
    if (endIndex < 0) throw new Error(`Missing character end marker in ${rulesFile}`);
    rules = rules.slice(0, rules.indexOf(start)) + markdown + rules.slice(endIndex + end.length).trimStart();
  } else rules = rules.trimEnd() + '\n\n' + markdown;
  await writeFile(rulesFile, rules);
}
console.log('Updated 13 bilingual character entries in guide and chat rules.');
